name: circle_tracker
description: Circle — Track your people in real-time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  geolocator:
  mapbox_maps_flutter:

  hive:
  hive_flutter:
  permission_handler:
  shared_preferences:
  uuid:
  http:
  sensors_plus:
  shimmer:
  share_plus:
  url_launcher:
  package_info_plus:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/.gitkeep
    - assets/icons/.gitkeep
