name: vortex_dashboard
description: Motorcycle/car dashboard with GPS, compass, altimeter & tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  geolocator:
  flutter_map:

  hive:
  hive_flutter:
  fl_chart:
  permission_handler:
  shared_preferences:
  uuid:
  intl:
  http:
  path_provider:
  sensors_plus:
  geocoding:
  latlong2:
  equatable:
  freezed_annotation:
  json_annotation:
  xml:
  csv:
  wakelock_plus:
  smooth_page_indicator:
  shimmer:
  share_plus:
  url_launcher:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  freezed:
  json_serializable:
  riverpod_generator:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png
  adaptive_icon_background: '#0a0f1e'
  adaptive_icon_foreground: assets/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/.gitkeep
    - assets/icons/.gitkeep
